
using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.Genetics.UI
{

    [GenerateTypedNameReferences]
    public sealed partial class BreedStationWindow : FancyWindow
    {
        [Dependency] private readonly IPrototypeManager _prototypeManager = default!;

        public BreedStationWindow()
        {
            RobustXamlLoader.Load(this);
        }
    }
}
